using Unity.Netcode;
using UnityEngine;
using static RandomUtil;

public class AnimalVariator : NetworkBehaviour
{
    [Header("References")]
    public Renderer rend;
    public Antler antler;

    [Header("Settings")]
    public float albinoChance = 0.005f; // base for color variation

    public AnimalPelt pelt;
    public bool male;

    // The seed generated by the server and replicated to all clients
    private NetworkVariable<int> seed = new NetworkVariable<int>(0, NetworkVariableReadPermission.Everyone, NetworkVariableWritePermission.Server);

    private bool appearanceApplied = false;

    public override void OnNetworkSpawn()
    {
        if (IsServer)
        {
            if (seed.Value == 0)
            {
                seed.Value = Random.Range(1, 100000);
                Debug.Log($"[Server] Animal seed generated: {seed.Value}");
            }

            ApplyAppearance(seed.Value);
        }
        else
        {
            // Clients wait until the seed is valid before applying appearance
            StartCoroutine(WaitForSeedAndApply());
        }
    }

    private System.Collections.IEnumerator WaitForSeedAndApply()
    {
        // Wait until seed syncs (Netcode ensures eventual consistency)
        yield return new WaitUntil(() => seed.Value != 0);

        if (!appearanceApplied)
        {
            ApplyAppearance(seed.Value);
            Debug.Log($"[Client] Applied appearance using seed {seed.Value}");
        }
    }

    // public void SetSeed()
    // {
    //     if (IsServer)
    //     {
    //         // Generate seed once on the server
    //         seed.Value = Random.Range(0, 100000);
    //         ApplyAppearance(seed.Value);
    //         Debug.Log("Seed set to " + seed.Value);
    //     }
    //     else
    //     {
    //         Debug.LogError("Non server attempted to set seed of an animal");
    //     }
    // }

    private void ApplyAppearance(int seedValue)
    {
        System.Random rng = new System.Random(seedValue);

        Debug.Log("Animal generating with seed " + seedValue);

        // Determine pelt
        pelt = GetPeltVariant(rng);
        ApplyColor(pelt.Color);

        // Determine sex
        male = RandomBool(rng);

        // Determine antlers if male
        if (antler != null && male)
        {
            antler.Initialize(seedValue);
        }
    }

    private void ApplyColor(Color c)
    {
        if (rend != null && rend.materials.Length > 0)
        {
            rend.materials[0].color = c;
        }
    }

    private AnimalPelt GetPeltVariant(System.Random rng)
    {
        Color baseColor = rend.materials[0].color;

        // Albino check
        if (RandomRangeFloat(rng, 0f, 1f) < albinoChance)
        {
            float shade = RandomRangeFloat(rng, 0.85f, 1f);
            Color albinoColor = new Color(shade, shade * 0.95f, shade * 0.9f);
            return new AnimalPelt(albinoColor, "Albino");
        }

        // HSV variation from base color
        Color.RGBToHSV(baseColor, out float h, out float s, out float v);

        float hOffset = RandomRangeFloat(rng, -0.02f, 0.02f);
        float sOffset = RandomRangeFloat(rng, -0.05f, 0.05f);
        float vOffset = RandomRangeFloat(rng, -0.05f, 0.05f);

        float newH = Mathf.Repeat(h + hOffset, 1f);
        float newS = Mathf.Clamp01(s + sOffset);
        float newV = Mathf.Clamp01(v + vOffset);

        Color newColor = Color.HSVToRGB(newH, newS, newV);

        string desc;
        if (newV < 0.35f) desc = "Dark Brown";
        else if (newV < 0.55f) desc = "Brown";
        else desc = "Light Brown";

        Debug.Log("Animal pelt generated with colour " + newColor.ToString() + " " + desc);

        return new AnimalPelt(newColor, desc);
    }

    public AnimalPelt GetPelt() => pelt;

    public Antler GetAntler() => antler;
}
